### ISSUE TITLE
Arcore sample not working with ARCore 1.12.0

### ISSUE THREAD

**Issue by knightcube** [wrld3d/wrld-unity-ar-samples#1]
I get these error when I tried ARCore 1.12.0 -
 Assets/Wrld SDK Samples/Common/Scripts/WRLDARStreamingCameraHandler.cs(27,50): error CS0103: The name `Wrld' does not exist in the current context

PPtr cast failed when dereferencing! Casting from PrefabInstance to Prefab!

**Comment by ArslanJafri** [comment]
From the error it looks like Wrld Unity SDK is missing. Can you please confirm that you have imported the Wrld Unity SDK in your project? ARCore Sample need both Wrld and ARCore packages to work. Wrld SDK can be downloaded from http://cdn1.eegeo.com/unity/wrld.unity.sdk.0.7.1019.release.unitypackage
Full instructions for setting up the ARCore project can be found here: https://wrld3d.com/unity/latest/docs/examples/device-deployment-arcore/

**Comment by ghost** [comment]
User never replied.  AR code will be revised in next release, so closing to avoid future confusion.
